"""Constants for the OCPP Charger Simulator integration."""

DOMAIN = "ocpp_charger"
CONF_BASE_URL = "base_url"
CONF_ENERGY_ENTITY = "energy_entity_id"
CONF_POWER_ENTITY = "power_entity_id"
CONF_CURRENT_ENTITY = "current_entity_id"
CONF_SOC_ENTITY = "soc_entity_id"
CONF_STATUS_ENTITY = "status_entity_id"
CONF_CONNECTED_VALUE = "connected_value"
CONF_DISCONNECTED_VALUE = "disconnected_value"
CONF_CONNECTED_STATUS = "connected_status"
CONF_DISCONNECTED_STATUS = "disconnected_status"

DEFAULT_BASE_URL = "http://localhost:5000"
DEFAULT_CONNECTED_VALUE = "on"
DEFAULT_DISCONNECTED_VALUE = "off"
DEFAULT_CONNECTED_STATUS = "Charging"
DEFAULT_DISCONNECTED_STATUS = "Available"
